import Head from "next/head"
export default function Layout({ children }) {
    return (
        <div className="flex flex-col">
            <Head>
                <title>cms</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>heder</div>
            <main className="flex flex-col">{children}</main>
            <div>footer</div>
        </div>

    )
}